# Generated by Django 3.2 on 2023-12-22 18:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='物料名称')),
                ('max_inventory', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大库存')),
                ('min_inventory', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='最小库存')),
                ('now_inventory', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='当前库存')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='物料描述')),
                ('picture', models.ImageField(null=True, upload_to='upload_images', verbose_name='物料图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='物料价格')),
                ('now_datetime', models.DateTimeField(auto_now=True, verbose_name='入库时间')),
                ('supplier', models.CharField(max_length=15, verbose_name='供应商')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
            },
        ),
        migrations.CreateModel(
            name='OutInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_way', models.CharField(max_length=8, verbose_name='去向途径')),
                ('out_datetime', models.DateTimeField(auto_now=True, verbose_name='出库时间')),
                ('supplier', models.CharField(max_length=20, verbose_name='消耗单位')),
                ('num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='出库数量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OutInventory', to='cms.material', verbose_name='物料序号')),
            ],
            options={
                'verbose_name': '出库',
                'verbose_name_plural': '出库',
            },
        ),
        migrations.CreateModel(
            name='InInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='入库数量')),
                ('source', models.CharField(max_length=10, verbose_name='来源')),
                ('in_datetime', models.DateTimeField(auto_now=True, verbose_name='入库时间')),
                ('in_supplier', models.CharField(max_length=15, verbose_name='供应商')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InInventory', to='cms.material', verbose_name='物料名称')),
            ],
            options={
                'verbose_name': '入库',
                'verbose_name_plural': '入库',
            },
        ),
        migrations.CreateModel(
            name='CheckInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='盘点日期')),
                ('num', models.IntegerField(verbose_name='库存数量')),
                ('actual_num', models.IntegerField(verbose_name='实际数量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckInventory', to='cms.material', verbose_name='物料序号')),
            ],
            options={
                'verbose_name': '盘点',
                'verbose_name_plural': '盘点',
            },
        ),
    ]
