# Generated by Django 3.2 on 2023-12-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ininventory',
            options={'verbose_name': '入库', 'verbose_name_plural': '入库'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '物料', 'verbose_name_plural': '物料'},
        ),
        migrations.RenameField(
            model_name='outinventory',
            old_name='out_datatime',
            new_name='out_datetime',
        ),
    ]
